# Generated by Django 2.1.7 on 2019-03-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
    ]
